### ISSUE TITLE
checking for version of wiringPI in install script

### ISSUE THREAD

**Issue by MrYsLab** [nebrius/raspi-wiringpi#3]
Currently the install script just checks to see if wiringPi was previously installed, but does not check to see if the version number is compatible with the version of raspi-io.

What happens in the future, if raspi-io requires either a wiringPI bug fix update or feature update?

**Comment by nebrius** [comment]
So an update on this, I _think_ that Raspbian Jesse ships with Wiring Pi now. In a fresh install I did `npm install raspi-io` and my install script said "Wiring Pi already installed, skipping...". Now I haven't looked in to this any further, but this may mean that this module can go away entirely eventually!

**Comment by fivdi** [comment]
This may be the case with Raspbian. Not sure about other distributions and [this issue](https://github.com/nebrius/raspi-io/issues/24) though.

**Comment by nebrius** [comment]
I always forget about other OSes 😅

**Comment by nebrius** [comment]
Closing as raspi-wiringpi was removed from raspi
